/* Pharmacology lecture supplement. All clinical statements below are limited to the supplied Psych Pharm lecture deck and previously approved course sources. */
const pharmObjectives=[
 {t:'Know the pharmacology',d:'Mechanism of action, indications, dose/route, common effects, serious adverse effects, precautions, contraindications, limitations, and interactions.'},
 {t:'Choose and sequence treatment',d:'First-line and later-line pharmacologic/nonpharmacologic treatment by condition, acuity, response, and phase of illness.'},
 {t:'Match the patient',d:'Apply age, renal/hepatic function, nutrition, pregnancy, comorbidity, concurrent drugs, misuse risk, cost, and patient preference.'},
 {t:'Counsel and monitor',d:'Explain administration, delayed onset, adherence, adverse-effect management, interactions, warning symptoms, and required follow-up.'},
 {t:'Distinguish the classes',d:'Recognize class mechanisms and select the specific drug whose clinical pearl best fits the vignette.'},
 {t:'Recognize emergencies',d:'Identify serotonin syndrome, neuroleptic malignant syndrome, lithium toxicity, severe rash, withdrawal, respiratory depression, and other lecture-highlighted hazards.'}
];

const pharmClassGuides=[
 {t:'Neurotransmitter primer',b:'Acetylcholine supports parasympathetic signaling, neuromuscular transmission, learning, and memory; excess produces salivation/lacrimation/urination/diarrhea, miosis, bradycardia, and bronchoconstriction. Catecholamines follow tyrosine → L-dopa → dopamine → norepinephrine → epinephrine and are metabolized by monoamine oxidase. Dopamine supports reward/motivation and is central to Parkinson disease and psychosis models. Serotonin influences mood, sleep, appetite, pain, and gastrointestinal function. Gamma-aminobutyric acid (GABA) is inhibitory; benzodiazepines, barbiturates, and alcohol enhance GABA-A signaling.',s:'Psych Pharm lecture, slides 3–8'},
 {t:'MDD treatment by severity',b:'For mild major depressive disorder (MDD), the lecture guideline summary supports cognitive behavioral therapy (CBT) alone or another nonpharmacologic approach, with medication based on guideline and patient preference. Moderate-to-severe MDD generally uses an SSRI/SNRI or another first-line antidepressant, with psychotherapy alone or combined; the National Institute for Health and Care Excellence summary favors CBT plus SSRI/SNRI for more severe illness. Other nonpharmacologic options listed include interpersonal, problem-solving, and psychodynamic therapy, light therapy, acupuncture, bibliotherapy, and meditation.',s:'Psych Pharm lecture, slides 12 and 14'},
 {t:'Depressogenic medication check',b:'Medication contributors are cautions—not automatic contraindications. The lecture highlights beta-blockers (especially propranolol), alcohol, estrogen, progestins, and varenicline, and also lists clonidine, methyldopa, selected antiepileptic/Parkinson drugs, chronic opioids, tamoxifen, anabolic steroids, isotretinoin, interferon, antiretrovirals, atomoxetine, and methylphenidate. Confirm timing and weigh medical necessity/alternatives before assigning causality.',s:'Psych Pharm lecture, slide 13'},
 {t:'Antidepressant treatment course & switching',b:'Acute treatment starts low and may be titrated weekly. Physical symptoms may improve in 1–2 weeks, mood in 2–4 weeks, and maximal effect in about 4–6 weeks. Continue 4–9 months after response; maintenance may be lifelong after more than 3 episodes. After an adequate 4–8-week failure, switch when there is no response and augment a partial response. A monoamine oxidase inhibitor (MAOI) needs a 2-week washout. Taper selective serotonin reuptake inhibitors (SSRIs) and serotonin–norepinephrine reuptake inhibitors (SNRIs), usually over 2–4 weeks; short half-life, high dose, and use beyond 4 weeks raise withdrawal risk.',s:'Psych Pharm lecture, slides 10–13 and 28–31'},
 {t:'Serotonin syndrome & antidepressant safety',b:'All antidepressants carry the lecture-highlighted suicidality warning in patients younger than 25, especially at initiation and dose changes. Serotonin syndrome usually develops rapidly within 1–24 hours: autonomic instability, mental-status change, diarrhea, tremor, myoclonus, rigidity, and hyperreflexia. Risk is greatest with serotonergic combinations, especially an MAOI combination.',s:'Psych Pharm lecture, slides 12 and 31–34'},
 {t:'Anxiety sequence & benzodiazepine rule',b:'For generalized anxiety disorder, combine psychoeducation/cognitive behavioral therapy (CBT) with an SSRI or SNRI first line. Start at roughly half the depression dose and titrate slowly; continue 6–12 months. Reserve a benzodiazepine for severe short-term symptoms (about 2–3 weeks). Hydroxyzine can substitute short term; buspirone and pregabalin are alternatives/add-ons. Benzodiazepines increase gamma-aminobutyric acid type A (GABA-A) signaling, can cause sedation, amnesia, dependence, respiratory depression, and withdrawal seizures, and should not be stopped abruptly.',s:'Psych Pharm lecture, slides 35–47'},
 {t:'Anxiety treatment by diagnosis',b:'Panic disorder: SSRI/SNRI with or without a short benzodiazepine bridge first line; clomipramine or imipramine second line. Social anxiety: cognitive behavioral therapy is preferred; escitalopram/sertraline are leading medication choices, with fluvoxamine/paroxetine/venlafaxine alternatives. PTSD: psychotherapy is preferred; paroxetine, sertraline, or venlafaxine are medication options, and prazosin may target nightmares; avoid benzodiazepines. OCD: fluvoxamine, fluoxetine, sertraline, or paroxetine; clomipramine second line, often with higher doses/longer trials.',s:'Psych Pharm lecture, slide 50'},
 {t:'Benzodiazepine withdrawal & taper',b:'Withdrawal can begin within hours to 3 days and may last up to 2 weeks; severe withdrawal includes seizures. The lecture taper example reduces the dose by 25% weekly until 50% remains, then by 10–12.5% every 4–7 days. After use longer than 1 year, tapering may require 3–4 months. Flumazenil can provoke seizures/arrhythmias and is generally not used.',s:'Psych Pharm lecture, slides 42–43'},
 {t:'Insomnia & narcolepsy framework',b:'Cognitive behavioral therapy for insomnia and sleep hygiene are first line. Identify sleep-onset versus sleep-maintenance difficulty; goals are more total sleep, faster sleep onset, and fewer awakenings. Use the lowest effective dose, especially in older adults, and keep hypnotics short term—the lecture suggests 3–4 nights/week for 3–4 weeks. Z-drugs are preferred over benzodiazepines because of lower abuse/dependence/tolerance risk but still carry a boxed warning for complex sleep behavior. Benzodiazepines suppress rapid eye movement (REM) sleep and cross the placenta. Narcolepsy care adds planned daytime naps, counseling, and avoidance of sedating or insomnia-provoking drugs.',s:'Psych Pharm lecture, slides 51–68'},
 {t:'Antipsychotic class map',b:'First-generation antipsychotics (FGAs) block dopamine D2 receptors and treat positive symptoms, with more extrapyramidal symptoms (EPS) and hyperprolactinemia. Second-generation antipsychotics (SGAs) generally block D2 and serotonin 5-HT2 receptors and have more metabolic burden. Highest metabolic risk: clozapine > olanzapine > quetiapine > risperidone/paliperidone. Highest QT risk: haloperidol, ziprasidone, thioridazine. Highest prolactin risk: risperidone/paliperidone. Clozapine is the most effective option after failure of at least 2 antipsychotics.',s:'Psych Pharm lecture, slides 73–87'},
 {t:'Antipsychotic patient selection',b:'In older adults, use the lowest effective dose if clinically necessary, avoid anticholinergic/orthostatic burden when possible, and remember the dementia-related psychosis increased-mortality boxed warning; quetiapine is favored with Parkinson disease in the lecture. Pregnancy/lactation are described as generally compatible with case-by-case discussion; if an FGA is used, higher potency limits anticholinergic, sedating, and hypotensive effects. Other lecture uses include major-depression augmentation, mood disorders with psychosis, bipolar disorder, agitation/delirium, and Tourette syndrome.',s:'Psych Pharm lecture, slides 89–90'},
 {t:'Neuroleptic malignant syndrome (NMS)',b:'Suspect NMS after antipsychotic initiation or dose increase when fever, diaphoresis, lead-pipe rigidity, delirium, and autonomic instability evolve over 1–3 days. Risks include high dose, rapid titration, dehydration, and exhaustion. Stop the offending drug, give fluids/cooling, monitor creatine phosphokinase and renal function, and consider benzodiazepines, dantrolene, or bromocriptine.',s:'Psych Pharm lecture, slide 88'},
 {t:'Bipolar treatment by phase',b:'Acute mania: lithium, valproate, or an SGA first line; carbamazepine/oxcarbazepine second line. Bipolar depression options in the lecture include lithium, lamotrigine, lurasidone, quetiapine, or olanzapine/fluoxetine. Maintenance choices depend on the pole being prevented. Quetiapine has data across acute mania, acute depression, and maintenance. Do not use an antidepressant alone because it may induce mania; lamotrigine is not useful for acute mania because it requires slow titration.',s:'Psych Pharm lecture, slides 93–106'},
 {t:'ADHD treatment selection',b:'For school-aged children older than 6, stimulants plus educational/behavioral interventions are first-line medical treatment. Methylphenidate is better tolerated; amphetamine is slightly more effective. Reassess periodically for the lowest effective dose. Nonstimulants suit concern for diversion, illicit-substance history in the patient/household, or caregiver preference. Improvement on a stimulant is not diagnostic for attention-deficit/hyperactivity disorder (ADHD).',s:'Psych Pharm lecture, slides 107–112'},
 {t:'Smoking cessation sequence',b:'Use the 5 As: Ask, Advise, Assess, Assist, Arrange. Counseling plus medication outperforms either alone; treatment is usually at least 3 months. First-line choices are varenicline or dual nicotine replacement therapy (NRT: patch plus gum/lozenge); bupropion is a somewhat less effective but reasonable alternative. If the first option fails, switch to another first-line option.',s:'Psych Pharm lecture, slides 113–117'}
];
window.pharmObjectives=pharmObjectives;
window.pharmClassGuides=pharmClassGuides;

const B={
 ssri:{g:'Antidepressants · SSRI',moa:'Selective serotonin reuptake inhibition increases synaptic serotonin.',uses:'First-line depression and common first-line long-term anxiety treatment; agent-specific uses are listed below.',common:'Nausea (most common), diarrhea/anorexia, headache, activation/insomnia or sedation, sexual dysfunction.',serious:'Suicidality warning under age 25; syndrome of inappropriate antidiuretic hormone secretion (SIADH)/hyponatremia, bleeding, serotonin syndrome, and discontinuation symptoms.',cautions:'Assess bipolar polarity and suicidality; taper rather than abruptly stop.',interactions:'Avoid unsafe serotonergic combinations and MAOI overlap.',monitor:'Mood, suicidality, activation, sodium when clinically indicated, bleeding, sexual effects, and withdrawal.'},
 snri:{g:'Antidepressants · SNRI',moa:'Inhibits serotonin and norepinephrine reuptake.',uses:'First-line alternative for depression/generalized anxiety; may help fatigue or neuropathic pain.',common:'SSRI-like gastrointestinal, sleep, and sexual effects plus norepinephrine-related effects.',serious:'Suicidality warning under age 25, serotonin syndrome, withdrawal, increased blood pressure/heart rate, glaucoma concern.',cautions:'Reduce dose with renal impairment as directed in the lecture; avoid or closely assess uncontrolled/labile hypertension.',interactions:'Avoid MAOI overlap and unsafe serotonergic combinations.',monitor:'Blood pressure, heart rate, mood/suicidality, activation, and discontinuation symptoms.'},
 bzd:{g:'Anxiety & sleep · Benzodiazepine',moa:'Positive allosteric modulation of GABA-A receptors increases chloride-channel opening frequency.',uses:'Rapid, short-term relief of severe anxiety; agent-specific sleep, seizure, or alcohol-withdrawal roles below.',common:'Sedation, dizziness, cognitive impairment, and amnesia.',serious:'Tolerance, dependence/addiction, withdrawal seizures, falls, and respiratory depression—especially with opioids or other central nervous system depressants.',cautions:'Avoid in acute angle-closure glaucoma, severe respiratory insufficiency, and severe liver disease; use extra caution in older adults.',interactions:'Opioids can cause profound sedation, respiratory depression, coma, or death. Avoid alcohol/other sedatives.',monitor:'Sedation, breathing, falls, cognition, use duration, misuse, and withdrawal; taper rather than stop abruptly.'},
 zdrug:{g:'Sleep · Z-drug',moa:'Preferential alpha-1 GABA-A receptor hypnotic activity.',uses:'Short-term insomnia; distinguish sleep-onset from sleep-maintenance needs.',common:'Somnolence, dizziness, and ataxia.',serious:'Boxed warning for complex sleep behaviors such as sleep-driving; withdrawal with use beyond 2 weeks.',cautions:'Allow 7–8 hours for sleep and account for greater next-day sedation in women.',interactions:'Alcohol and other central nervous system depressants increase impairment.',monitor:'Complex sleep behavior, next-day function, falls, duration, and dependence.'},
 orexin:{g:'Sleep · Orexin antagonist',moa:'Blocks orexin receptors, reducing wake-promoting signaling.',uses:'Insomnia.',common:'Somnolence and next-day impairment.',serious:'Abnormal thinking/behavior, worsening depression or suicidal ideation, sleep paralysis, hallucinations, and hazardous sleep-related activity.',cautions:'Contraindicated in narcolepsy; requires at least 7 hours available for sleep.',interactions:'Cytochrome P450 3A4 (CYP3A4) substrate per lecture.',monitor:'Mood, unusual behavior, paralysis/hallucinations, complex sleep behavior, and daytime impairment.'},
 fga:{g:'Antipsychotics · FGA',moa:'Dopamine D2 receptor antagonism; binding at muscarinic M1, histamine H1, and alpha-1 receptors varies by potency.',uses:'Positive symptoms of schizophrenia; selected acute agitation/mania roles.',common:'EPS and hyperprolactinemia; lower-potency agents add more sedation, orthostasis, and anticholinergic effects.',serious:'Tardive dyskinesia, NMS, QT prolongation, and dangerous dystonia.',cautions:'Higher potency increases EPS risk. Older adults with dementia-related psychosis have an increased-mortality boxed warning.',interactions:'Additive QT, hypotension, anticholinergic, or sedating effects.',monitor:'Abnormal movements, prolactin symptoms, weight/metabolic measures, orthostasis, and electrocardiogram (ECG) when risk warrants.'},
 sga:{g:'Antipsychotics · SGA',moa:'D2 and 5-HT2 receptor antagonism for most agents; partial D2 agonists are identified below.',uses:'Schizophrenia; selected bipolar, augmentation, agitation, and other agent-specific roles.',common:'Weight, lipid, glucose, sedation, orthostasis, EPS, or prolactin effects vary by agent.',serious:'NMS, tardive dyskinesia, QT prolongation, and agent-specific boxed warnings.',cautions:'Older adults with dementia-related psychosis have an increased-mortality boxed warning.',interactions:'Agent-specific food, smoking, and CYP effects are listed below.',monitor:'Weight, waist/body mass index as locally used, blood pressure, glucose, lipids, movements, prolactin symptoms, orthostasis, and QT risk.'},
 stimulant:{g:'ADHD · Stimulant',moa:'Blocks presynaptic norepinephrine and dopamine reuptake; amphetamines also directly release dopamine.',uses:'First-line medical treatment for ADHD in school-aged children older than 6 with educational/behavioral interventions.',common:'Decreased appetite, insomnia, weight loss, dizziness, nightmares, and blood-pressure change.',serious:'Poor growth, psychosis, bone loss, rare tics, dependence, diversion/misuse; withdrawal may cause fatigue, hypersomnia, hyperphagia, and vivid dreams.',cautions:'Schedule II; assess misuse/diversion and use the lowest effective dose.',interactions:'Review concurrent stimulants and other drugs affecting blood pressure, sleep, or psychiatric status.',monitor:'Appetite, weight/growth, sleep, blood pressure, function, psychosis/tics, and diversion.'}
};
const m=(x,base)=>Object.assign({},base||{},x);

window.pharmMedications=[
 m({n:'Citalopram',brand:'Celexa',dose:'20–40 mg by mouth daily; maximum 20 mg/day in older adults.',uses:'Major depressive disorder; lecture also lists it among SSRI options for generalized anxiety disorder.',serious:'Class risks plus QTc prolongation.',pearl:'The SSRI with the clearest lecture-highlighted QT dose ceiling.',s:'Psych Pharm lecture, slides 14–16, 37'},B.ssri),
 m({n:'Escitalopram',brand:'Lexapro',dose:'10 mg by mouth daily; maximum 10 mg/day in older adults.',uses:'Major depressive disorder and first-line generalized/social anxiety options in the lecture.',serious:'Class risks; less QT concern than citalopram.',pearl:'Often the cleaner citalopram comparison when QT risk matters.',s:'Psych Pharm lecture, slides 14–16, 37, 50'},B.ssri),
 m({n:'Fluoxetine',brand:'Prozac',dose:'10–60 mg by mouth each morning.',uses:'Major depressive disorder; Food and Drug Administration (FDA)-approved for bulimia nervosa; lecture options for generalized anxiety, social anxiety, obsessive-compulsive disorder (OCD), and cataplexy add-on.',common:'Activating; least weight gain among the compared SSRIs; class gastrointestinal and sexual effects.',interactions:'Strong CYP2D6 inhibitor; avoid MAOI overlap and unsafe serotonergic combinations.',pearl:'Long half-life means fewer withdrawal symptoms; dose in the morning.',s:'Psych Pharm lecture, slides 14–16, 37, 50, 68'},B.ssri),
 m({n:'Paroxetine',brand:'Paxil',dose:'10–60 mg by mouth daily (lecture generalized-anxiety range 10–50 mg/day).',uses:'Major depressive disorder; anxiety indications including panic, social anxiety, posttraumatic stress disorder (PTSD), and OCD in lecture tables.',common:'Anticholinergic and sedating; most weight gain and sexual dysfunction among the compared SSRIs.',serious:'Class risks; pregnancy caution emphasized in the lecture and prominent withdrawal risk.',pearl:'A poor fit when anticholinergic burden, weight gain, sexual effects, pregnancy, or missed-dose withdrawal are major concerns.',s:'Psych Pharm lecture, slides 14–16, 37, 50'},B.ssri),
 m({n:'Sertraline',brand:'Zoloft',dose:'50–200 mg by mouth daily; generalized-anxiety starting range in lecture 25–200 mg/day.',uses:'Major depressive disorder; first-line options for generalized anxiety, panic disorder, social anxiety, PTSD, and OCD.',common:'Gastrointestinal adverse effects; mildly activating.',cautions:'Take with food.',pearl:'Preferred SSRI in the lecture when cardiac risk is important.',s:'Psych Pharm lecture, slides 14–16, 37, 50'},B.ssri),
 m({n:'Fluvoxamine',brand:'Luvox',dose:'No agent-specific dose is supplied in this lecture.',uses:'Named in the SSRI class and as an OCD/social-anxiety option.',pearl:'Course emphasis is its OCD/social-anxiety placement rather than a separate dosing table.',s:'Psych Pharm lecture, slides 14 and 50'},B.ssri),

 m({n:'Venlafaxine',brand:'Effexor',dose:'Immediate release 37.5–375 mg/day; extended release up to 225 mg/day.',uses:'Depression, generalized anxiety, panic disorder, social anxiety, PTSD, and cataplexy add-on.',common:'At lower doses behaves more like an SSRI; greater norepinephrine effect at higher doses.',serious:'Highest lecture-highlighted blood-pressure risk, especially above 150 mg/day; class withdrawal risk.',cautions:'Avoid in uncontrolled/labile hypertension and glaucoma.',monitor:'Blood pressure every 2–6 months per lecture, plus class monitoring.',s:'Psych Pharm lecture, slides 17–19, 37, 50, 68'},B.snri),
 m({n:'Desvenlafaxine',brand:'Pristiq',dose:'No agent-specific dose is supplied in this lecture.',uses:'Named as an SNRI for depression/anxiety class review.',pearl:'The lecture teaches it at class level; distinguish it from the detailed venlafaxine card.',s:'Psych Pharm lecture, slide 17'},B.snri),
 m({n:'Duloxetine',brand:'Cymbalta',dose:'40–60 mg/day or 20–30 mg twice daily; doses above 60 mg are not more effective in the lecture.',uses:'Depression/anxiety plus FDA pain indications including neuropathy and fibromyalgia; cataplexy add-on listed.',common:'Class effects plus anticholinergic effects.',serious:'Hepatotoxicity.',cautions:'Consider liver risk and class renal-dose guidance.',s:'Psych Pharm lecture, slides 17–19, 37, 68'},B.snri),
 m({n:'Levomilnacipran',brand:'Fetzima',dose:'No agent-specific dose is supplied in this lecture.',uses:'Named as an SNRI for class recognition.',pearl:'Course coverage is class identification rather than agent-specific selection.',s:'Psych Pharm lecture, slide 17'},B.snri),

 m({n:'Bupropion',brand:'Wellbutrin; Zyban',dose:'Depression: extended release 300–450 mg daily; immediate release three times daily or sustained release twice daily. Smoking cessation timing is below.',moa:'Norepinephrine–dopamine reuptake inhibitor and nicotinic antagonist.',uses:'First-line major depression, seasonal affective disorder, smoking cessation, SSRI/SNRI augmentation, and off-label ADHD.',common:'Activating, anxiety/insomnia, dry mouth, tremor, headache, nausea, possible weight loss; little sexual dysfunction.',serious:'Lowers seizure threshold; suicidality warning under age 25; hypertension and high-dose psychosis noted.',cautions:'Contraindicated with seizure disorder, anorexia nervosa, bulimia nervosa, or abrupt alcohol discontinuation.',interactions:'CYP2D6 inhibition; may combine with SSRI/SNRI to reduce sexual adverse effects. Can combine with NRT.',monitor:'Mood/suicidality, anxiety, sleep, blood pressure, seizure risk, eating-disorder/alcohol history.',pearl:'Smoking: start 1–2 weeks before quit date and continue 7–12 weeks; a reasonable choice with depression or concern about weight gain.',s:'Psych Pharm lecture, slides 21–22, 29, 116'},null),
 m({n:'Mirtazapine',brand:'Remeron',dose:'15–45 mg by mouth nightly; use a low dose below 22.5 mg when leveraging sedation for sleep.',moa:'Alpha-2 antagonist increases norepinephrine and serotonin; strong H1 blockade is more sedating at lower doses.',uses:'Major depression/anxiety; useful with insomnia, poor intake, or frailty.',common:'Sedation, appetite increase, weight gain, anticholinergic effects; less sexual dysfunction.',serious:'QT concern and antidepressant suicidality warning.',monitor:'Weight/appetite, sedation/falls, mood/suicidality, QT risk when relevant.',pearl:'The “sleep + appetite + low weight” antidepressant fit.',s:'Psych Pharm lecture, slides 23 and 61'},null),
 m({n:'Trazodone',brand:'Desyrel',dose:'Depression 150–300 mg/day divided; insomnia 12.5–50 mg in antidepressant slide and 50–100 mg nightly in insomnia table.',moa:'Serotonin reuptake inhibition plus H1 and alpha-1 blockade.',uses:'Depression; low-dose off-label insomnia.',common:'Sedation and orthostatic hypotension/falls; sexual dysfunction.',serious:'Priapism lasting more than 4 hours requires emergency care; antidepressant suicidality warning.',monitor:'Sedation, orthostasis/falls, mood, and priapism counseling.',pearl:'Low-dose use is for sleep; antidepressant dosing is much higher.',s:'Psych Pharm lecture, slides 24 and 61'},null),
 m({n:'Vortioxetine',brand:'Trintellix',dose:'5–20 mg by mouth daily.',moa:'Serotonin reuptake inhibition, 5-HT1A agonism, and 5-HT3 antagonism.',uses:'Major depressive disorder.',common:'Nausea/vomiting; less sexual dysfunction in the lecture.',serious:'Antidepressant suicidality and serotonergic class risks.',monitor:'Mood/suicidality, gastrointestinal effects, sexual effects, and serotonin toxicity.',s:'Psych Pharm lecture, slide 24'},null),
 m({n:'Vilazodone',brand:'Viibryd',dose:'10–20 mg by mouth daily.',moa:'Serotonin reuptake inhibition plus 5-HT1A partial agonism.',uses:'Major depressive disorder.',common:'Serotonergic gastrointestinal and activation effects.',serious:'Antidepressant suicidality and serotonin-syndrome risk.',cautions:'Take with food.',monitor:'Mood/suicidality, adherence with food, and serotonergic effects.',s:'Psych Pharm lecture, slide 24'},null),
 m({n:'Nefazodone',brand:'Serzone',dose:'200–600 mg/day divided twice daily.',moa:'Serotonin/norepinephrine reuptake inhibition with 5-HT2 and alpha-1 antagonism.',uses:'Major depression; rarely used.',common:'Less sedating than trazodone in the lecture.',serious:'Boxed warning for hepatotoxicity.',monitor:'Liver risk/symptoms and mood/suicidality.',pearl:'Rarely used because the liver warning dominates the risk–benefit decision.',s:'Psych Pharm lecture, slide 24'},null),

 m({n:'Amitriptyline',brand:'Elavil',dose:'No agent-specific dose is supplied in this lecture.',moa:'Tricyclic antidepressant (TCA): inhibits norepinephrine/serotonin reuptake and blocks muscarinic and H1 receptors.',uses:'Second-line depression; neuropathic pain, migraine, and insomnia roles.',common:'Anticholinergic effects, sedation, weight gain, confusion, orthostasis, and sexual dysfunction.',serious:'Arrhythmia, QT prolongation/torsades, fatal overdose, and suicidality warning under age 25.',cautions:'High overdose and anticholinergic burden.',monitor:'Cardiac/overdose risk, anticholinergic burden, orthostasis, sedation, and suicidality.',s:'Psych Pharm lecture, slides 25–26'},null),
 m({n:'Doxepin',brand:'Sinequan; Silenor',dose:'Insomnia: 6 mg nightly; 3 mg if older than 65.',moa:'TCA; at low sleep doses, sedation is leveraged.',uses:'Second-line depression and low-dose insomnia.',common:'Somnolence and possible anticholinergic effects.',serious:'TCA cardiac/overdose risks at antidepressant exposure and antidepressant suicidality warning.',cautions:'The lecture identifies low-dose doxepin as safe for older adults; the insomnia brand is expensive.',monitor:'Sedation/falls, anticholinergic and cardiac risk according to dose/context.',s:'Psych Pharm lecture, slides 25–26 and 61'},null),
 m({n:'Nortriptyline',brand:'Pamelor',dose:'No agent-specific dose is supplied in this lecture.',moa:'Secondary-amine TCA inhibiting norepinephrine/serotonin reuptake.',uses:'Second-line depression and class pain/migraine roles.',common:'TCA anticholinergic, sedation, orthostasis, weight, confusion, and sexual effects.',serious:'Arrhythmia/QT/torsades and potentially fatal overdose.',monitor:'Cardiac and overdose risk, anticholinergic effects, and suicidality.',s:'Psych Pharm lecture, slides 25–26'},null),
 m({n:'Clomipramine',brand:'Anafranil',dose:'No agent-specific dose is supplied in this lecture.',moa:'TCA with serotonergic reuptake inhibition.',uses:'Second-line option for panic disorder and OCD in the lecture.',common:'TCA anticholinergic, sedating, orthostatic, weight, and sexual effects.',serious:'Cardiac/QT and overdose toxicity; serotonergic toxicity and suicidality warning.',monitor:'Cardiac/overdose risk, anticholinergic burden, and response after an adequate OCD trial.',s:'Psych Pharm lecture, slides 25–26 and 50'},null),
 m({n:'Imipramine',brand:'Tofranil',dose:'No agent-specific dose is supplied in this lecture.',moa:'TCA inhibiting norepinephrine and serotonin reuptake.',uses:'Second-line option for panic disorder in the lecture.',common:'TCA anticholinergic, sedation, orthostasis, weight, and sexual effects.',serious:'Arrhythmia/QT/torsades and potentially fatal overdose.',monitor:'Cardiac/overdose risk, anticholinergic effects, and suicidality.',s:'Psych Pharm lecture, slides 25–26 and 50'},null),

 ...['Selegiline|Emsam','Rasagiline|Azilect','Phenelzine|Nardil','Tranylcypromine|Parnate','Isocarboxazid|Marplan'].map(pair=>{const [n,brand]=pair.split('|');return m({n,brand,dose:'No agent-specific dose is supplied in this lecture.',moa:'Irreversible monoamine oxidase inhibition increases monoamine signaling.',uses:'Refractory or atypical depression/anxiety class role.',common:'Insomnia, weight gain, orthostasis, and sexual dysfunction.',serious:'Serotonin syndrome with interacting drugs and tyramine-triggered hypertensive crisis.',cautions:'Requires a 2-week washout when switching; extensive food/drug restrictions limit use.',interactions:'Avoid serotonergic overlap. Avoid high-tyramine foods/drinks; a reaction may begin within 20–60 minutes.',monitor:'Blood pressure symptoms, orthostasis, diet/interaction understanding, and mood/suicidality.',s:'Psych Pharm lecture, slides 27–31'})}),

 m({n:'Diazepam',brand:'Valium',dose:'4–40 mg/day by mouth.',uses:'Short-term severe anxiety; seizure-related uses in the lecture.',pearl:'Long acting and fast onset; higher abuse concern.',s:'Psych Pharm lecture, slides 38–43'},B.bzd),
 m({n:'Clonazepam',brand:'Klonopin',dose:'0.5–12 mg/day by mouth.',uses:'Short-term severe anxiety/panic and seizure-related uses.',pearl:'Long acting.',s:'Psych Pharm lecture, slides 38–43'},B.bzd),
 m({n:'Alprazolam',brand:'Xanax',dose:'0.5–6 mg/day by mouth.',uses:'Short-term severe anxiety/panic.',pearl:'Fast onset and short duration increase rebound/abuse concern.',s:'Psych Pharm lecture, slides 38–43'},B.bzd),
 m({n:'Lorazepam',brand:'Ativan',dose:'Anxiety 1.5–6 mg/day; insomnia 0.5–2 mg nightly.',uses:'Short-term severe anxiety, alcohol withdrawal, and insomnia.',cautions:'One of the LOT agents (lorazepam, oxazepam, temazepam) favored when hepatic metabolism is a concern.',pearl:'Intermediate duration; the lecture’s benzodiazepine “hepatic-safe” memory anchor.',s:'Psych Pharm lecture, slides 38–43 and 55'},B.bzd),
 m({n:'Temazepam',brand:'Restoril',dose:'7.5–30 mg nightly.',uses:'Insomnia.',cautions:'One of the LOT agents favored when hepatic metabolism is a concern.',pearl:'Sleep-focused benzodiazepine; not for long-term insomnia.',s:'Psych Pharm lecture, slides 38–43 and 55'},B.bzd),
 m({n:'Chlordiazepoxide',brand:'Librium',dose:'10–100 mg/day by mouth.',uses:'Alcohol withdrawal.',pearl:'Course-specific role is alcohol withdrawal, not chronic anxiety management.',s:'Psych Pharm lecture, slides 38–43'},B.bzd),
 m({n:'Estazolam',brand:'ProSom',dose:'1–2 mg nightly.',uses:'Insomnia.',pearl:'The lecture lists it among benzodiazepine hypnotics; apply the full class dependence/fall/respiratory cautions.',s:'Psych Pharm lecture, slide 55'},B.bzd),
 m({n:'Triazolam',brand:'Halcion',dose:'0.125–0.5 mg nightly.',uses:'Insomnia.',pearl:'Short-acting sleep benzodiazepine; rebound/withdrawal and amnesia are key class concerns.',s:'Psych Pharm lecture, slide 55'},B.bzd),
 m({n:'Flurazepam',brand:'Dalmane',dose:'No agent-specific dose is supplied in this lecture.',uses:'Named as a benzodiazepine hypnotic.',pearl:'Course coverage is class-level; apply Schedule IV dependence, pregnancy, fall, cognitive, and respiratory cautions.',s:'Psych Pharm lecture, slide 57'},B.bzd),
 m({n:'Quazepam',brand:'Doral',dose:'No agent-specific dose is supplied in this lecture.',uses:'Named as a benzodiazepine hypnotic.',pearl:'Course coverage is class-level; apply Schedule IV dependence, pregnancy, fall, cognitive, and respiratory cautions.',s:'Psych Pharm lecture, slide 57'},B.bzd),
 m({n:'Flumazenil',brand:'Romazicon',dose:'No dose supplied in this lecture.',moa:'Benzodiazepine receptor antagonist.',uses:'Antidote concept for benzodiazepine effects.',common:'The lecture emphasizes risk rather than routine benefit.',serious:'Can precipitate seizures and arrhythmias.',cautions:'Generally not used according to the lecture because reversal can be dangerous.',monitor:'Airway/breathing and seizure/arrhythmia risk in any considered use.',s:'Psych Pharm lecture, slide 42'},null),
 m({n:'Hydroxyzine',brand:'Atarax; Vistaril',dose:'25–100 mg up to four times daily as needed.',moa:'Histamine H1 receptor antagonist.',uses:'Short-term anxiety alternative, including when substance-use risk makes benzodiazepines undesirable.',common:'Sedation and anticholinergic effects; cognitive impairment/amnesia.',serious:'Respiratory depression concern with other depressants.',cautions:'Avoid in older adults when possible because of anticholinergic/sedating burden.',interactions:'Additive effects with central nervous system depressants.',monitor:'Sedation, cognition, falls, anticholinergic effects, and breathing risk.',s:'Psych Pharm lecture, slide 44'},null),
 m({n:'Buspirone',brand:'Buspar',dose:'10 mg twice daily, then twice or three times daily; maximum 60 mg/day.',moa:'5-HT1A partial agonist with dopamine antagonism.',uses:'Second-line generalized anxiety; useful in older adults or substance-use risk and may augment an antidepressant.',common:'Dizziness, drowsiness, headache, and nausea.',serious:'Not presented as dependence-forming in the lecture.',cautions:'Onset takes 2–6 weeks; not for immediate relief.',interactions:'May be combined with antidepressants, while serotonergic burden still requires review.',monitor:'Adherence through delayed onset, dizziness, nausea, and anxiety response.',s:'Psych Pharm lecture, slide 45'},null),
 m({n:'Pregabalin',brand:'Lyrica',dose:'150–600 mg/day divided.',moa:'Indirectly increases inhibitory GABA-related signaling per lecture.',uses:'Second-line/alternative or add-on for anxiety; also seizure and neuropathic-pain indications.',common:'Sedation, dizziness, edema, and weight gain.',serious:'Schedule V misuse/abuse potential.',cautions:'Not FDA-approved for anxiety in the lecture.',monitor:'Sedation, edema, weight, response, and misuse.',pearl:'Faster onset than buspirone/antidepressants in the lecture.',s:'Psych Pharm lecture, slide 46'},null),
 m({n:'Propranolol',brand:'Inderal',dose:'10–40 mg about 1 hour before a performance.',moa:'Nonselective beta-adrenergic receptor blocker.',uses:'Performance-related autonomic anxiety symptoms; also appears in prior course material for akathisia/lithium tremor.',common:'Dizziness and confusion listed as central nervous system effects.',serious:'Blood-pressure/heart-rate lowering.',cautions:'Not FDA-approved for anxiety; treats peripheral symptoms rather than the cognitive core.',monitor:'Pulse, blood pressure, dizziness, and event-specific benefit.',s:'Psych Pharm lecture, slide 47; CMDT Ch 28'},null),
 m({n:'Prazosin',brand:'Minipress',dose:'No dose supplied in this lecture.',moa:'Alpha-1 adrenergic receptor antagonist.',uses:'PTSD-related nightmares.',common:'Orthostatic symptoms are the practical course concern.',serious:'Hypotension/syncope risk.',monitor:'Blood pressure, orthostasis, falls, and nightmare response.',s:'Psych Pharm lecture, slide 50; CMDT Ch 28'},null),

 m({n:'Eszopiclone',brand:'Lunesta',dose:'1–3 mg nightly.',s:'Psych Pharm lecture, slides 52–54'},B.zdrug),
 m({n:'Zolpidem',brand:'Ambien',dose:'5–10 mg nightly; maximum 5 mg in women and older adults per lecture.',pearl:'Dose reduction addresses next-day sedation risk.',s:'Psych Pharm lecture, slides 52–54'},B.zdrug),
 m({n:'Zaleplon',brand:'Sonata',dose:'5–10 mg nightly.',uses:'Primarily sleep-onset insomnia; may not improve total sleep time.',pearl:'Less daytime sedation, but shorter action may not maintain sleep.',s:'Psych Pharm lecture, slides 52–54'},B.zdrug),
 m({n:'Melatonin',brand:'Multiple OTC brands',dose:'1–10 mg by mouth; can dose as the sun goes down.',moa:'Acts at melatonin receptors supporting sleepiness/circadian timing.',uses:'Best lecture evidence is for jet lag.',common:'Somnolence and dizziness.',serious:'No controlled-substance warning in lecture.',monitor:'Timing, next-day sedation, and benefit.',s:'Psych Pharm lecture, slides 57–59'},null),
 m({n:'Ramelteon',brand:'Rozerem',dose:'8 mg by mouth nightly.',moa:'Melatonin MT1/MT2 agonist with higher affinity for MT1.',uses:'Sleep-onset insomnia.',common:'Somnolence and dizziness.',cautions:'Minimal increase in total sleep time (about 20 minutes in the lecture).',pearl:'Not a controlled substance.',s:'Psych Pharm lecture, slides 57–59'},null),
 m({n:'Tasimelteon',brand:'Hetlioz',dose:'20 mg by mouth nightly.',moa:'Melatonin MT1/MT2 agonist.',uses:'Non-24-hour sleep–wake disorder; not approved for insomnia in the lecture.',common:'Somnolence and dizziness.',pearl:'Not a controlled substance.',s:'Psych Pharm lecture, slides 57–59'},null),
 m({n:'Suvorexant',brand:'Belsomra',dose:'10 mg nightly; maximum 20 mg/day.',pearl:'Schedule IV; at least 7 hours of sleep required.',s:'Psych Pharm lecture, slide 60'},B.orexin),
 m({n:'Lemborexant',brand:'Dayvigo',dose:'No agent-specific dose is supplied in this lecture.',pearl:'Schedule IV orexin antagonist; apply the class narcolepsy contraindication.',s:'Psych Pharm lecture, slide 60'},B.orexin),
 m({n:'Daridorexant',brand:'Quviviq',dose:'No agent-specific dose is supplied in this lecture.',pearl:'Schedule IV orexin antagonist; apply the class narcolepsy contraindication.',s:'Psych Pharm lecture, slide 60'},B.orexin),
 m({n:'Doxylamine',brand:'Unisom',dose:'25 mg nightly.',moa:'Sedating H1 antihistamine.',uses:'Short-term over-the-counter insomnia use.',common:'Anticholinergic effects, sedation, and confusion; paradoxical excitation in young children.',cautions:'Avoid in older adults; more sedating and longer-lasting than diphenhydramine, with daytime sedation.',monitor:'Next-day impairment, confusion, falls, and anticholinergic effects.',s:'Psych Pharm lecture, slide 62'},null),
 m({n:'Diphenhydramine',brand:'Benadryl',dose:'25–50 mg nightly as needed.',moa:'Sedating H1 antihistamine.',uses:'Short-term over-the-counter insomnia use.',common:'Anticholinergic effects, sedation, and confusion; paradoxical excitation in young children.',cautions:'Avoid in older adults. Use only in brief stretches because tolerance develops quickly.',pearl:'Less daytime sedation than doxylamine in the lecture.',s:'Psych Pharm lecture, slide 62'},null),
 m({n:'Valerian root',brand:'Multiple supplements',dose:'No dose supplied; not an as-needed agent and requires 1–2 weeks for benefit.',moa:'Not specified in the lecture.',uses:'Herbal insomnia option discussed by the lecture.',cautions:'Both American Academy of Sleep Medicine and Veterans Affairs summaries in the lecture recommend against it.',monitor:'Benefit, sedation, and supplement use disclosure.',s:'Psych Pharm lecture, slides 63–64'},null),
 m({n:'Kava-kava',brand:'Multiple supplements',dose:'No dose supplied.',moa:'Not specified in the lecture.',uses:'Limited insomnia data.',serious:'Can cause liver failure.',cautions:'Avoid; the Veterans Affairs guideline summary recommends against it.',monitor:'Avoidance and liver-risk counseling.',s:'Psych Pharm lecture, slides 63–64'},null),

 m({n:'Modafinil',brand:'Provigil',dose:'200 mg by mouth daily.',moa:'Stimulant effect through dopamine-transporter blockade, increasing brain dopamine.',uses:'Narcolepsy; shift-work sleep disorder; off-label adjunct for major depression with severe fatigue/hypersomnia and other fatigue syndromes listed.',common:'Anorexia, nausea, dyspepsia, headache, and insomnia.',serious:'Potentially life-threatening severe rash/Stevens–Johnson syndrome.',cautions:'Schedule IV.',monitor:'Rash, appetite, sleep, headache, and benefit.',s:'Psych Pharm lecture, slide 67'},null),
 m({n:'Armodafinil',brand:'Nuvigil',dose:'150–250 mg by mouth daily.',moa:'Stimulant effect through dopamine-transporter blockade.',uses:'Narcolepsy and shift-work sleep disorder class roles.',common:'Anorexia, nausea, dyspepsia, headache, and insomnia.',serious:'Potentially life-threatening severe rash/Stevens–Johnson syndrome.',cautions:'Schedule IV.',monitor:'Rash, appetite, sleep, headache, and benefit.',s:'Psych Pharm lecture, slide 67'},null),
 m({n:'Sodium oxybate',brand:'Xyrem',dose:'2.25 g at bedtime and again 2.5–4 hours later; effective total 6–9 g/night. Mix in ¼ cup water, lie down immediately, and remain in bed.',moa:'GABA metabolite acting at GABA receptor sites.',uses:'Narcolepsy with cataplexy under the lecture’s restricted program.',common:'Dizziness, confusion, and nausea.',serious:'Boxed warning: strong central nervous system depression, respiratory depression, coma, and death.',cautions:'Schedule III for narcolepsy and Schedule I for illicit use; Risk Evaluation and Mitigation Strategy (REMS) access required in the lecture.',interactions:'Avoid other central nervous system depressants.',monitor:'Breathing, consciousness, misuse, administration safety, and REMS compliance.',pearl:'Onset 5–15 minutes; the second nighttime dose is part of the regimen.',s:'Psych Pharm lecture, slide 68'},null),

 m({n:'Haloperidol',brand:'Haldol',dose:'No numeric dose supplied; by mouth, short-acting intramuscular lactate, or long-acting intramuscular decanoate. Intravenous use is off-label and protocol-dependent.',uses:'Schizophrenia positive symptoms and common inpatient acute-agitation use; also acute mania.',serious:'High EPS and QT risk; QT risk is intravenous > intramuscular > oral.',pearl:'Most common FGA in the lecture; decanoate is the long-acting injectable.',s:'Psych Pharm lecture, slides 78–80, 86'},B.fga),
 m({n:'Fluphenazine',brand:'Prolixin',dose:'No numeric dose supplied; oral, short-acting intramuscular hydrochloride, or long-acting intramuscular decanoate.',uses:'Schizophrenia positive symptoms; rarely used.',pearl:'Second most common FGA in the lecture, though current use is described as very rare.',s:'Psych Pharm lecture, slides 78–79'},B.fga),
 ...['Trifluoperazine|Stelazine','Loxapine|Loxitane','Perphenazine|Trilafon'].map(pair=>{const [n,brand]=pair.split('|');return m({n,brand,dose:'No agent-specific dose or route is supplied in this lecture.',uses:'Named FGA for schizophrenia class recognition.',pearl:'The lecture teaches this agent at class level; apply the FGA EPS/prolactin versus potency framework.',s:'Psych Pharm lecture, slide 78'},B.fga)}),
 m({n:'Chlorpromazine',brand:'Thorazine',dose:'No numeric dose supplied; oral, intramuscular, or intravenous routes listed.',uses:'Rarely used for schizophrenia; lecture notes use for nausea and migraines.',common:'Very sedating with orthostatic hypotension and anticholinergic effects.',pearl:'Low-potency FGA: more H1/M1/alpha-1 burden.',s:'Psych Pharm lecture, slides 78–79'},B.fga),
 m({n:'Thioridazine',brand:'Mellaril',dose:'No agent-specific dose or route is supplied in this lecture.',uses:'Named low-potency FGA.',serious:'Among the highest QT-prolongation risks in the lecture.',pearl:'Remember QT risk rather than routine first-line use.',s:'Psych Pharm lecture, slides 78 and 86'},B.fga),

 m({n:'Risperidone',brand:'Risperdal',dose:'4–16 mg/day by mouth; long-acting injectable available (Risperdal Consta).',uses:'Schizophrenia; bipolar option and long-acting maintenance option.',common:'Somnolence, orthostasis; weight, lipid, and glucose increases.',serious:'Dose-dependent EPS above 6 mg and high hyperprolactinemia risk.',monitor:'Class metabolic/movement monitoring plus prolactin symptoms and slow titration for orthostasis.',s:'Psych Pharm lecture, slides 82, 86–87, 96'},B.sga),
 m({n:'Paliperidone',brand:'Invega',dose:'3–12 mg/day by mouth; long-acting injectable available (Invega Sustenna).',uses:'Schizophrenia.',common:'Similar to risperidone: somnolence/orthostasis and metabolic effects.',serious:'Increased prolactin and higher-dose EPS.',pearl:'Active metabolite of risperidone.',s:'Psych Pharm lecture, slides 82 and 86'},B.sga),
 m({n:'Ziprasidone',brand:'Geodon',dose:'40–160 mg/day divided twice daily.',uses:'Schizophrenia; short-acting injectable available.',common:'Somnolence, dizziness, and nausea; less significant weight gain.',serious:'High QTc-prolongation risk; lecture lists QT risk as a contraindication.',cautions:'Take with food.',monitor:'ECG/QT risk, food adherence, movements, and class metabolic measures.',s:'Psych Pharm lecture, slides 82, 86–87'},B.sga),
 m({n:'Quetiapine',brand:'Seroquel',dose:'400–800 mg/day divided twice daily or extended release nightly.',uses:'Schizophrenia; lecture-preferred antipsychotic across acute mania, acute bipolar depression, and maintenance; FDA-approved adjunct in major depression.',common:'Somnolence (sometimes leveraged for sleep), orthostasis, weight/lipid/glucose increases.',serious:'Lower EPS and lower QT risk than many comparators, but substantial metabolic burden.',pearl:'Most broadly phase-spanning bipolar antipsychotic in the lecture.',s:'Psych Pharm lecture, slides 83, 86–87, 95–96'},B.sga),
 m({n:'Olanzapine',brand:'Zyprexa',dose:'10–20 mg by mouth nightly; short-acting and long-acting injectable formulations listed.',uses:'Schizophrenia, acute agitation, bipolar mania; olanzapine/fluoxetine (Symbyax) for bipolar depression.',common:'Somnolence and marked weight, lipid, and glucose increases.',serious:'Among the highest metabolic risks; low EPS risk and lower QT risk.',interactions:'Smoking can reduce drug levels.',monitor:'Intensive weight/glucose/lipid monitoring plus smoking-status changes.',s:'Psych Pharm lecture, slides 83, 86–87, 95–96'},B.sga),
 m({n:'Lurasidone',brand:'Latuda',dose:'40–160 mg/day by mouth.',uses:'Schizophrenia and bipolar depression.',common:'High akathisia risk but low other-EPS risk; less sedation.',serious:'Minimal QT and near-neutral weight/lipid/glucose profile in the lecture.',cautions:'Take with more than 350 calories.',pearl:'Food requirement + bipolar-depression role + lower metabolic burden.',s:'Psych Pharm lecture, slides 83 and 87, 95, 105'},B.sga),
 m({n:'Aripiprazole',brand:'Abilify',dose:'10–30 mg by mouth each morning; long-acting injectable available (Abilify Maintena).',moa:'Partial D2 and 5-HT1A agonism with serotonin-receptor effects.',uses:'Schizophrenia; bipolar and major-depression augmentation roles.',common:'Akathisia, anxiety, and insomnia; less sedation.',serious:'Least metabolic burden in the lecture, though some QT concern is noted.',pearl:'Think partial agonist, activating/akathisia, and metabolically lighter.',s:'Psych Pharm lecture, slides 84 and 87, 95'},B.sga),
 m({n:'Brexpiprazole',brand:'Rexulti',dose:'2–4 mg by mouth daily.',moa:'Partial D2 agonist.',uses:'Schizophrenia and FDA-approved adjunct in major depression per lecture.',common:'Weight gain, dyspepsia, diarrhea, and akathisia.',serious:'Lower metabolic burden than high-risk SGAs but still monitor class effects.',pearl:'Similar mechanism to aripiprazole; course table emphasizes gastrointestinal effects, weight, and akathisia.',s:'Psych Pharm lecture, slides 84 and 95'},B.sga),
 m({n:'Clozapine',brand:'Clozaril',dose:'Start 12.5 mg and titrate; 300–900 mg/day divided.',uses:'Treatment-resistant schizophrenia after failure of at least 2 antipsychotics; reduces suicide/depression incidence in lecture summary.',common:'Sedation, excessive drooling, orthostasis/bradycardia, and major metabolic effects.',serious:'Boxed warnings highlighted for severe neutropenia, myocarditis/cardiomyopathy, seizures, and cardiovascular collapse risks; very low EPS.',cautions:'Re-titrate if held 48 hours. Lecture notes the clozapine REMS program was removed in June 2025, but absolute neutrophil count (ANC) monitoring remains.',interactions:'Smoking reduces drug levels.',monitor:'Baseline ANC above 1500/mm³, weekly ANC for 6 months per lecture, stop if ANC below 1000/mm³; monitor myocarditis, seizures, orthostasis, and metabolic effects.',pearl:'Most effective antipsychotic, but not first line because safety monitoring dominates.',s:'Psych Pharm lecture, slides 81, 85–87'},B.sga),
 ...['Asenapine|Saphris','Iloperidone|Fanapt','Cariprazine|Vraylar'].map(pair=>{const [n,brand]=pair.split('|');return m({n,brand,dose:'No agent-specific dose or route is supplied in this lecture.',uses:'Named SGA for class recognition.',pearl:'The lecture does not provide an agent-specific comparison; apply the SGA mechanism and monitoring framework.',s:'Psych Pharm lecture, slide 81'},B.sga)}),
 m({n:'Dantrolene',brand:'Dantrium',dose:'No dose supplied in this lecture.',moa:'Muscle-relaxation treatment named for NMS.',uses:'Adjunctive treatment for severe NMS after stopping the offending drug and providing fluids/cooling.',monitor:'Rigidity, temperature, respiratory status, creatine phosphokinase, and renal function in emergency care.',s:'Psych Pharm lecture, slide 88'},null),
 m({n:'Bromocriptine',brand:'Parlodel',dose:'No dose supplied in this lecture.',moa:'Dopamine agonist.',uses:'Named pharmacologic option for NMS.',monitor:'NMS clinical response and emergency-care parameters.',s:'Psych Pharm lecture, slide 88'},null),

 m({n:'Lithium',brand:'Lithobid',dose:'Start 150–900 mg/day divided three times daily; usual maximum 900–1800 mg/day divided three to four times daily.',moa:'Moderates excitatory glutamate and influences serotonin/norepinephrine reuptake.',uses:'First- or second-line acute mania and maintenance; less favored for acute depressive episodes.',common:'Polydipsia, polyuria, weight gain, hypothyroidism, blue-gray skin pigmentation, and inverted T waves.',serious:'Narrow therapeutic index. Above 1.5 mEq/L: coarse tremor, vomiting, persistent diarrhea, confusion, ataxia; above 2.5: central nervous system depression, arrhythmia, seizure, irreversible injury, coma, death.',cautions:'100% renal elimination; pregnancy avoidance emphasized. Acute target may reach 1.5 mEq/L; maintenance 0.8–1.2 mEq/L in lecture.',interactions:'Diuretics, angiotensin-converting enzyme inhibitors/angiotensin receptor blockers, nonsteroidal anti-inflammatory drugs, dehydration, and low sodium can increase levels.',monitor:'Basic metabolic panel (sodium/creatinine), thyroid tests every 3 months twice then yearly, complete blood count baseline/yearly, pregnancy, ECG, and levels. Keep salt intake consistent; drink 8–12 glasses of fluid; avoid NSAIDs.',s:'Psych Pharm lecture, slides 97–99'},null),
 m({n:'Lamotrigine',brand:'Lamictal',dose:'Start 25 mg/day; 50–400 mg/day divided, following a slow titration pack.',moa:'Antiepileptic that inhibits glutamate release and voltage-gated sodium channels.',uses:'First-line maintenance prevention of depressive episodes and second-line acute bipolar depression.',common:'Headache, sedation, nausea, vomiting, and diarrhea.',serious:'Boxed warning for Stevens–Johnson syndrome/toxic epidermal necrolysis.',cautions:'Not useful for acute mania or manic-episode maintenance because titration must be gradual.',interactions:'Valproic acid increases lamotrigine levels; use a lower starting dose and slower titration if combined.',monitor:'Any rash—especially mucosal/systemic symptoms—requires prompt evaluation; verify titration and interacting drugs.',s:'Psych Pharm lecture, slides 100 and 102, 105'},null),
 m({n:'Valproic acid / valproate',brand:'Depakene; Depacon',dose:'10–15 mg/kg/day; maximum 60 mg/kg/day.',moa:'Antiepileptic that increases GABA release and inhibits voltage-gated sodium channels.',uses:'Acute mania; lecture notes it is now less preferred and has less maintenance evidence.',common:'Sedation, weakness, dizziness, weight gain, nausea/vomiting/diarrhea, polycystic ovary syndrome, amenorrhea, thrombocytopenia, and alopecia.',serious:'Boxed warnings: hepatotoxicity, pancreatitis, teratogenicity, and mitochondrial disease.',interactions:'Raises lamotrigine levels; estrogen-containing contraceptives can decrease valproate levels.',monitor:'Liver tests, platelets, pregnancy, and level 50–100 mcg/mL; correct interpretation for low albumin.',s:'Psych Pharm lecture, slide 102'},null),
 m({n:'Divalproex',brand:'Depakote; Depakote ER; Depakote Sprinkle',dose:'10–15 mg/kg/day; maximum 60 mg/kg/day.',moa:'Valproate formulation increasing GABA release and inhibiting voltage-gated sodium channels.',uses:'Acute mania; less evidence for maintenance in the lecture.',common:'Sedation, weakness, dizziness, weight gain, gastrointestinal effects, polycystic ovary syndrome, amenorrhea, thrombocytopenia, and alopecia.',serious:'Boxed warnings: hepatotoxicity, pancreatitis, teratogenicity, and mitochondrial disease.',interactions:'Raises lamotrigine levels; estrogen-containing contraceptives can decrease valproate exposure.',monitor:'Liver tests, platelets, pregnancy, and level 50–100 mcg/mL; correct for low albumin.',s:'Psych Pharm lecture, slide 102'},null),
 m({n:'Carbamazepine',brand:'Tegretol',dose:'200 mg twice daily; maximum 1600 mg/day.',moa:'Antiepileptic inhibiting voltage-gated sodium and N-methyl-D-aspartate (NMDA) glutamate receptors.',uses:'Second- or third-line acute mania; less maintenance evidence.',common:'Sedation, weight gain, hepatotoxicity, and hyponatremia.',serious:'Boxed warnings for Stevens–Johnson syndrome/toxic epidermal necrolysis and agranulocytosis/aplastic anemia.',interactions:'Major drug interactions as a CYP3A4 inducer.',monitor:'Blood count, liver/sodium status, rash, interactions, and levels when clinically used.',s:'Psych Pharm lecture, slide 103'},null),
 m({n:'Oxcarbazepine',brand:'Trileptal',dose:'300 mg twice daily; maximum 1200 mg/day.',moa:'Carbamazepine derivative inhibiting voltage-gated sodium and NMDA glutamate receptors.',uses:'Second- or third-line acute mania; less maintenance evidence.',common:'Sedation, weight gain, hepatotoxicity, and hyponatremia (lecture ranks carbamazepine greater than oxcarbazepine).',serious:'Apply the lecture slide’s severe-rash/blood-dyscrasia class warnings with careful source review.',monitor:'Sodium, liver/blood effects, rash, and interactions.',s:'Psych Pharm lecture, slide 103'},null),

 m({n:'Methylphenidate',brand:'Ritalin; Concerta',dose:'No agent-specific dose is supplied in this lecture.',uses:'First-line ADHD medication for school-aged children older than 6; alternative stimulant for narcolepsy.',pearl:'Better tolerated than amphetamine in the lecture.',s:'Psych Pharm lecture, slides 67 and 110'},B.stimulant),
 m({n:'Dexmethylphenidate',brand:'Focalin',dose:'No agent-specific dose is supplied in this lecture.',uses:'Stimulant option for ADHD.',pearl:'Apply the same Schedule II, appetite/growth, sleep, blood-pressure, psychosis, and diversion monitoring.',s:'Psych Pharm lecture, slide 110'},B.stimulant),
 m({n:'Amphetamine/dextroamphetamine',brand:'Adderall',dose:'No agent-specific dose is supplied in this lecture.',moa:'Blocks norepinephrine/dopamine reuptake and directly releases dopamine.',uses:'First-line ADHD medication for school-aged children older than 6; stimulant alternative for narcolepsy.',pearl:'Slightly more effective than methylphenidate but less well tolerated in the lecture.',s:'Psych Pharm lecture, slides 67 and 110'},B.stimulant),
 m({n:'Atomoxetine',brand:'Strattera',dose:'No agent-specific dose is supplied in this lecture.',moa:'Selective norepinephrine reuptake inhibitor.',uses:'Nonstimulant ADHD alternative when diversion/illicit-substance risk or caregiver preference argues against a stimulant.',common:'Dry mouth, decreased appetite, and insomnia.',serious:'Hepatotoxicity; boxed warning for increased suicidal thinking in pediatric patients.',cautions:'Less effective than stimulants; onset may take up to 4 weeks.',monitor:'Suicidal thinking, liver symptoms, appetite/weight, sleep, and delayed response.',s:'Psych Pharm lecture, slide 111'},null),
 m({n:'Viloxazine',brand:'Qelbree',dose:'No agent-specific dose is supplied in this lecture.',moa:'Selective norepinephrine reuptake inhibitor.',uses:'Nonstimulant ADHD alternative when abuse/diversion or caregiver preference favors avoiding stimulants.',common:'Dry mouth, decreased appetite, and insomnia listed at class level.',cautions:'Delayed nonstimulant response framework; lecture gives no separate agent-specific warning table.',monitor:'Appetite/weight, sleep, psychiatric status, and response.',s:'Psych Pharm lecture, slide 111'},null),
 m({n:'Guanfacine extended release',brand:'Intuniv',dose:'No agent-specific dose is supplied in this lecture.',moa:'Presynaptic alpha-2 adrenergic agonism reduces excess norepinephrine release and strengthens prefrontal regulation.',uses:'ADHD when children respond poorly to stimulant or other nonstimulant trials.',common:'Hypotension, dizziness, sedation, and weight gain; less sedating than clonidine.',cautions:'Less effective than stimulants.',monitor:'Blood pressure, dizziness, sedation, weight, and response.',s:'Psych Pharm lecture, slide 112'},null),
 m({n:'Clonidine',brand:'Catapres',dose:'No agent-specific dose is supplied in this lecture.',moa:'Presynaptic alpha-2 adrenergic agonism reduces excess norepinephrine release.',uses:'ADHD when stimulant/nonstimulant trials respond poorly.',common:'Hypotension, dizziness, sedation, and weight gain; more sedating than guanfacine.',cautions:'Less effective than stimulants.',monitor:'Blood pressure, dizziness/falls, sedation, weight, and response.',s:'Psych Pharm lecture, slide 112'},null),

 m({n:'Varenicline',brand:'Chantix',dose:'Start 1 week before the quit date and continue about 4 months.',moa:'Partial agonist at alpha-4 beta-2 nicotinic acetylcholine receptors; reduces withdrawal while blocking nicotine reward.',uses:'First-line smoking cessation.',common:'Nausea, headache, and insomnia.',serious:'Lecture highlights increased suicidality and neuropsychiatric symptoms.',cautions:'Monitor patients with a depression history closely.',pearl:'Higher quit rates than bupropion or nicotine patch in the lecture.',s:'Psych Pharm lecture, slides 115–116'},null),
 m({n:'Nicotine gum',brand:'Nicorette',dose:'First cigarette within 30 minutes: 4 mg; later than 30 minutes: 2 mg. Minimum 9 pieces/day, maximum 24. Chew and park for 30 minutes.',moa:'Nicotine replacement reduces cravings and withdrawal without cigarette exposure.',uses:'Short-acting breakthrough component of first-line dual NRT.',common:'Local/oral adverse effects are not detailed in the lecture.',cautions:'Use caution with myocardial infarction within 2 weeks, arrhythmia, angina, pregnancy/breastfeeding, or age under 18.',pearl:'Pair with a long-acting patch for first-line dual NRT.',s:'Psych Pharm lecture, slide 117'},null),
 m({n:'Nicotine lozenge',brand:'Nicorette Lozenge',dose:'First cigarette within 30 minutes: 4 mg; later than 30 minutes: 2 mg. Minimum 9/day, maximum 20. Dissolve slowly; do not chew or swallow.',moa:'Nicotine replacement reduces cravings and withdrawal.',uses:'Short-acting breakthrough component of first-line dual NRT.',cautions:'Use caution with myocardial infarction within 2 weeks, arrhythmia, angina, pregnancy/breastfeeding, or age under 18.',pearl:'Pair with a long-acting patch for first-line dual NRT.',s:'Psych Pharm lecture, slide 117'},null),
 m({n:'Nicotine transdermal patch',brand:'NicoDerm CQ',dose:'More than 10 cigarettes/day: 21 mg × 6 weeks, 14 mg × 2 weeks, 7 mg × 2 weeks. Fewer than 10/day: 14 mg × 6 weeks, then 7 mg × 2 weeks.',moa:'Long-acting nicotine replacement provides sustained withdrawal relief.',uses:'First-line smoking cessation, ideally combined with gum or lozenge for breakthrough cravings.',cautions:'Use caution with myocardial infarction within 2 weeks, arrhythmia, angina, pregnancy/breastfeeding, or age under 18.',pearl:'Patch = baseline coverage; gum/lozenge = as-needed rescue.',s:'Psych Pharm lecture, slide 117'},null)
];

const pharmCategoryNames={
 'Antidepressants':['Bupropion','Mirtazapine','Trazodone','Vortioxetine','Vilazodone','Nefazodone','Amitriptyline','Doxepin','Nortriptyline','Clomipramine','Imipramine','Selegiline','Rasagiline','Phenelzine','Tranylcypromine','Isocarboxazid'],
 'Anxiety & sleep':['Flumazenil','Hydroxyzine','Buspirone','Pregabalin','Propranolol','Prazosin','Melatonin','Ramelteon','Tasimelteon','Doxylamine','Diphenhydramine','Valerian root','Kava-kava','Modafinil','Armodafinil','Sodium oxybate'],
 'Antipsychotics':['Dantrolene','Bromocriptine'],
 'Mood stabilizers':['Lithium','Lamotrigine','Valproic acid / valproate','Divalproex','Carbamazepine','Oxcarbazepine'],
 'ADHD':['Atomoxetine','Viloxazine','Guanfacine extended release','Clonidine'],
 'Smoking cessation':['Varenicline','Nicotine gum','Nicotine lozenge','Nicotine transdermal patch']
};
Object.entries(pharmCategoryNames).forEach(([category,names])=>window.pharmMedications.forEach(drug=>{if(!drug.g&&names.includes(drug.n))drug.g=category}));

window.pharmFlashcards=[
 ['Pharmacology','When should a partial antidepressant response be augmented rather than switched?','After an adequate 4–8-week trial, augment a partial response; switch when there is no response.','Psych Pharm lecture, slides 28–30'],
 ['Pharmacology','What is the rapid serotonin-syndrome pattern?','Within 1–24 hours: autonomic instability, mental-status change, diarrhea, tremor, myoclonus, rigidity, and hyperreflexia.','Psych Pharm lecture, slides 32–34'],
 ['Pharmacology','Which SSRI is activating, long acting, and least likely to cause withdrawal?','Fluoxetine (Prozac).','Psych Pharm lecture, slides 15–16'],
 ['Pharmacology','Which SSRI has the strongest lecture-highlighted QT dose ceiling?','Citalopram (Celexa); maximum 20 mg/day in older adults.','Psych Pharm lecture, slides 15–16'],
 ['Pharmacology','Which antidepressant fits insomnia, poor appetite, and frailty?','Mirtazapine (Remeron): lower doses leverage H1 sedation and it increases appetite/weight.','Psych Pharm lecture, slides 23 and 61'],
 ['Pharmacology','What are the LOT benzodiazepines?','Lorazepam, oxazepam, and temazepam—the lecture mnemonic for hepatic safety.','Psych Pharm lecture, slide 41'],
 ['Pharmacology','Which insomnia class is contraindicated in narcolepsy?','Orexin-receptor antagonists: suvorexant, lemborexant, and daridorexant.','Psych Pharm lecture, slide 60'],
 ['Pharmacology','Which narcolepsy drug requires two nighttime doses and a REMS program?','Sodium oxybate (Xyrem).','Psych Pharm lecture, slide 68'],
 ['Pharmacology','What adverse-effect tradeoff separates FGA from SGA antipsychotics?','FGAs have more EPS and less metabolic burden; SGAs generally have less EPS and more metabolic burden.','Psych Pharm lecture, slide 86'],
 ['Pharmacology','What makes clozapine the correct next step?','Persistent schizophrenia after adequate failure of at least 2 antipsychotics; it is the most effective treatment-resistant option.','Psych Pharm lecture, slides 81 and 85'],
 ['Pharmacology','What common factors increase lithium level?','Diuretics, ACE inhibitors/ARBs, NSAIDs, dehydration, and low sodium intake.','Psych Pharm lecture, slides 98–99'],
 ['Pharmacology','Why is lamotrigine not an acute-mania drug?','It must be titrated slowly to reduce SJS/TEN risk and is not effective for acute mania.','Psych Pharm lecture, slide 100'],
 ['Pharmacology','What is the ADHD stimulant class comparison?','Methylphenidate is better tolerated; amphetamine is slightly more effective.','Psych Pharm lecture, slide 110'],
 ['Pharmacology','What are the 2 preferred first-line smoking medication strategies?','Varenicline or dual NRT with a patch plus gum/lozenge.','Psych Pharm lecture, slides 115–117'],
 ['Pharmacology','Which nicotine dose is chosen when the first cigarette is within 30 minutes of waking?','4 mg gum or lozenge; use 2 mg if the first cigarette is later than 30 minutes.','Psych Pharm lecture, slide 117']
];

window.pharmReviewQuestions=[
 ['A 72-year-old with depression, insomnia, poor appetite, and weight loss wants one medication. Best fit?',['Fluoxetine','Bupropion','Mirtazapine','Venlafaxine'],2,'Mirtazapine is sedating and increases appetite/weight, matching the lecture vignette.','Psych Pharm lecture, slides 23, 61, 123'],
 ['A patient on haloperidol develops stiffness, tremor, and restlessness. Best adverse-effect category?',['Serotonin syndrome','Lithium toxicity','Extrapyramidal symptoms','Tyramine reaction'],2,'D2 blockade by an FGA commonly produces EPS.','Psych Pharm lecture, slides 75, 78, 120'],
 ['Which finding most strongly points to serotonin syndrome rather than NMS?',['Lead-pipe rigidity','Hyperreflexia with myoclonus and diarrhea','Gradual onset over 3 days','Recent antipsychotic increase'],1,'Serotonin syndrome is rapid and features hyperreflexia/myoclonus plus gastrointestinal activation.','Psych Pharm lecture, slides 32–34 and 88'],
 ['Which SSRI is most associated in the lecture with QTc dose limits?',['Sertraline','Fluoxetine','Citalopram','Paroxetine'],2,'Citalopram has the lecture-highlighted 20–40 mg range and lower older-adult maximum because of QTc.','Psych Pharm lecture, slides 15–16'],
 ['A partial response persists after an adequate antidepressant trial. Best general next strategy?',['Abruptly stop all drugs','Augment therapy','Always switch to an MAOI tomorrow','Declare treatment resistance immediately'],1,'The lecture recommends augmentation for partial response and switching for no response.','Psych Pharm lecture, slides 28–30'],
 ['Which drug can offset SSRI sexual dysfunction without adding much sexual adverse effect?',['Bupropion','Paroxetine','Clomipramine','Amitriptyline'],0,'Bupropion has little sexual dysfunction and is used as an augmenting option.','Psych Pharm lecture, slides 21–22 and 29'],
 ['Which anxiety drug has a 2–6 week onset and no abuse potential in the lecture?',['Alprazolam','Buspirone','Hydroxyzine','Propranolol'],1,'Buspirone is delayed rather than immediate and is useful when dependence risk matters.','Psych Pharm lecture, slide 45'],
 ['Which benzodiazepine is emphasized for alcohol withdrawal and safer hepatic handling?',['Alprazolam','Lorazepam','Clonazepam','Triazolam'],1,'Lorazepam is used for alcohol withdrawal and is one of the LOT agents.','Psych Pharm lecture, slides 40–41'],
 ['A patient taking a Z-drug begins sleep-driving. Best interpretation?',['Expected harmless effect','Boxed-warning complex sleep behavior','Serotonin syndrome','Lithium toxicity'],1,'Z-drugs carry a boxed warning for dangerous complex sleep behaviors.','Psych Pharm lecture, slides 52–54'],
 ['Which insomnia class is contraindicated in narcolepsy?',['Melatonin agonists','Orexin antagonists','Low-dose doxepin','Z-drugs'],1,'Orexin antagonists block wake-promoting signaling and are contraindicated in narcolepsy.','Psych Pharm lecture, slide 60'],
 ['A patient with cataplexy is prescribed a drug twice nightly under restricted access. Which drug?',['Modafinil','Sodium oxybate','Zolpidem','Ramelteon'],1,'Sodium oxybate is taken at bedtime and again 2.5–4 hours later through REMS.','Psych Pharm lecture, slide 68'],
 ['Which antipsychotic has the highest metabolic risk ranking in the lecture?',['Ziprasidone','Aripiprazole','Clozapine','Lurasidone'],2,'The ranking is clozapine > olanzapine > quetiapine > risperidone/paliperidone.','Psych Pharm lecture, slide 86'],
 ['Which antipsychotic must be taken with more than 350 calories?',['Lurasidone','Haloperidol','Aripiprazole','Clozapine'],0,'Food above 350 calories is a distinctive lurasidone administration pearl.','Psych Pharm lecture, slide 83'],
 ['Persistent schizophrenia remains severe after 3 adequate antipsychotic trials. Best next drug?',['Sertraline','Buspirone','Clozapine','Clonazepam'],2,'Clozapine is the most effective treatment-resistant option after at least 2 failures.','Psych Pharm lecture, slides 81, 85, 126'],
 ['Fever, delirium, autonomic instability, and lead-pipe rigidity after an antipsychotic increase suggest:',['NMS','SSRI withdrawal','Panic attack','Lithium tremor'],0,'This is the cardinal NMS pattern.','Psych Pharm lecture, slide 88'],
 ['Which factor is expected to increase lithium concentration?',['High sodium intake','Overhydration','NSAID use','Stopping a thiazide'],2,'NSAIDs reduce renal lithium elimination; dehydration, low sodium, diuretics, and ACE-I/ARBs also raise levels.','Psych Pharm lecture, slide 98'],
 ['Which bipolar medication is not useful for acute mania?',['Lithium','Valproate','Quetiapine','Lamotrigine'],3,'Lamotrigine requires slow titration and targets bipolar depression/maintenance, not acute mania.','Psych Pharm lecture, slides 100 and 105'],
 ['A patient taking valproate begins lamotrigine. What adjustment principle matters?',['Use a higher lamotrigine start','Lower and slow the lamotrigine titration','Stop all monitoring','Add an MAOI'],1,'Valproate raises lamotrigine levels, increasing rash risk.','Psych Pharm lecture, slide 102'],
 ['Which ADHD statement is accurate?',['Stimulant response proves ADHD','Amphetamine is better tolerated than methylphenidate','Methylphenidate is better tolerated; amphetamine is slightly more effective','Stimulants are not controlled substances'],2,'This is the lecture’s direct class comparison.','Psych Pharm lecture, slides 109–110'],
 ['A family is concerned about diversion. Which type is most appropriate to consider?',['A nonstimulant such as atomoxetine','Only short-acting amphetamine','A benzodiazepine','Lithium'],0,'Atomoxetine/viloxazine are alternatives when diversion or substance-use risk is a concern.','Psych Pharm lecture, slide 111'],
 ['Which alpha-2 ADHD agent is more sedating?',['Guanfacine','Clonidine','Atomoxetine','Viloxazine'],1,'The lecture ranks clonidine as more sedating than guanfacine.','Psych Pharm lecture, slide 112'],
 ['Which smoking strategy is first-line?',['Patch alone only','Varenicline or patch plus gum/lozenge','Bupropion only after all NRT fails','No medication for 3 months'],1,'Varenicline and dual NRT are the lecture’s preferred first-line options.','Psych Pharm lecture, slide 115'],
 ['A smoker lights the first cigarette 15 minutes after waking. Which gum starting strength?',['1 mg','2 mg','4 mg','7 mg'],2,'Within 30 minutes of waking corresponds to 4 mg gum or lozenge.','Psych Pharm lecture, slide 117'],
 ['Which smoking medication should begin 1 week before the quit date and continue about 4 months?',['Varenicline','Bupropion SR','Nicotine gum','Nicotine patch'],0,'That timing is the lecture regimen for varenicline.','Psych Pharm lecture, slide 116'],
 ['Which antidepressant is contraindicated with bulimia because of seizure risk?',['Escitalopram','Bupropion','Mirtazapine','Sertraline'],1,'Bupropion lowers seizure threshold and is contraindicated in bulimia/anorexia.','Psych Pharm lecture, slides 21–22 and 116']
];
